<?xml version="1.0" encoding="UTF-8"?>
<!--The following XML document is a "digital artifact" containing an XML element("conditions") that
identifies every condition that is generated by an implementation of ISO/IEC 39075.

An XML DTD is provided that may be used to validate the XML document itself. 

It may be used by implementers to specify the natural-language text that is reported whenever
any of the various conditions are generated by evaluation of GQL 
expressions and execution of GQL statements.  
It may also be used by documentation writers and translators to document those conditions in the 
natural languages of users of GQL-implementations.  
  -->

<!DOCTYPE conditions [

        <!-- The conditions element defines the conditions (completion or exception) for a set of standards.
        -->
        <!ELEMENT conditions ((class)*)>


        <!-- A class element defines the class code of an SQLSTATE or GQLSTATUS value.
        -->
        <!ELEMENT class ( ( subclass )* )>
        <!-- The attributes of class are:
              * category is the category of the class of conditions:
                - S - Successful Completion
                - N - No Data
                - W - Warning
                - I - Informational
                - X - Exception
              * code is the unique class code of the class of conditions.
              * name is the unique natural language name of the class of conditions.
        -->
        <!ATTLIST class
                category ( S | N | W | I | X) #REQUIRED
                code CDATA #REQUIRED
                name CDATA #REQUIRED
                >


        <!-- A subclass element defines the subclass code of an SQLSTATE or GQLSTATUS value.
        -->
        <!ELEMENT subclass (#PCDATA)>
        <!-- The attributes of subclass are:
              * code is the unique subclass code of the subclass within the class.
              * name is the unique natural language name of the subclass within the class.
        -->
        <!ATTLIST subclass
                code CDATA #REQUIRED
                name CDATA #REQUIRED
                >

        ]>

<conditions>
   <class category="S" code="00" name="successful completion">
      <subclass code="001" name="omitted result"/>
   </class>
   <class category="W" code="01" name="warning">
      <subclass code="004" name="string data, right truncation"/>
      <subclass code="G03" name="graph does not exist"/>
      <subclass code="G04" name="graph type does not exist"/>
      <subclass code="G11" name="null value eliminated in set function"/>
   </class>
   <class category="N" code="02" name="no data"/>
   <class category="I" code="03" name="informational"/>
   <class category="X" code="08" name="connection exception">
      <subclass code="007" name="transaction resolution unknown"/>
   </class>
   <class category="X" code="22" name="data exception">
      <subclass code="001" name="string data, right truncation"/>
      <subclass code="003" name="numeric value out of range"/>
      <subclass code="004" name="null value not allowed"/>
      <subclass code="007" name="invalid date, time, or, datetime format"/>
      <subclass code="008" name="datetime field overflow"/>
      <subclass code="011" name="substring error"/>
      <subclass code="012" name="division by zero"/>
      <subclass code="015" name="interval field overflow"/>
      <subclass code="018" name="invalid character value for cast"/>
      <subclass code="01E" name="invalid argument for natural logarithm"/>
      <subclass code="01F" name="invalid argument for power function"/>
      <subclass code="027" name="trim error"/>
      <subclass code="02F" name="array data, right truncation"/>
      <subclass code="G02" name="negative limit value"/>
      <subclass code="G03" name="invalid value type"/>
      <subclass code="G04" name="values not comparable"/>
      <subclass code="G05" name="invalid date, time, or datetime function field name"/>
      <subclass code="G06" name="invalid datetime function value"/>
      <subclass code="G07" name="invalid duration function field name"/>
      <subclass code="G0B" name="list data, right truncation"/>
      <subclass code="G0C" name="list element error"/>
      <subclass code="G0F" name="invalid number of paths or groups"/>
      <subclass code="G0H" name="invalid duration format"/>
      <subclass code="G0M" name="multiple assignments to a graph element property"/>
      <subclass code="G0N" name="number of node labels below supported minimum"/>
      <subclass code="G0P" name="number of node labels exceeds supported maximum"/>
      <subclass code="G0Q" name="number of edge labels below supported minimum"/>
      <subclass code="G0R" name="number of edge labels exceeds supported maximum"/>
      <subclass code="G0S" name="number of node properties exceeds supported maximum"/>
      <subclass code="G0T" name="number of edge properties exceeds supported maximum"/>
      <subclass code="G0U" name="record fields do not match"/>
      <subclass code="G0V" name="reference value, invalid base type"/>
      <subclass code="G0W" name="reference value, invalid constrained type"/>
      <subclass code="G0X" name="record data, field unassignable"/>
      <subclass code="G0Y" name="record data, field missing"/>
      <subclass code="G0Z" name="malformed path"/>
      <subclass code="G10" name="path data, right truncation"/>
      <subclass code="G11" name="reference value, referent deleted"/>
      <subclass code="G12" name="invalid value type"/>
      <subclass code="G13" name="invalid group variable value"/>
      <subclass code="G14" name="incompatible temporal instant unit groups"/>
   </class>
   <class category="X" code="25" name="invalid transaction state">
      <subclass code="G01" name="active GQL-transaction"/>
      <subclass code="G02" name="catalog and data statement mixing not supported"/>
      <subclass code="G03" name="read-only GQL-transaction"/>
      <subclass code="G04" name="accessing multiple graphs not supported"/>
   </class>
   <class category="X" code="2D" name="invalid transaction termination"/>
   <class category="X" code="40" name="transaction rollback">
      <subclass code="003" name="statement completion unknown"/>
   </class>
   <class category="X" code="42" name="syntax error or access rule violation">
      <subclass code="001" name="invalid syntax"/>
      <subclass code="002" name="invalid reference"/>
      <subclass code="004" name="use of visually confusable identifiers"/>
      <subclass code="006" name="number of edge labels below supported minimum"/>
      <subclass code="007" name="number of edge labels exceeds supported maximum"/>
      <subclass code="008" name="number of edge properties exceeds supported maximum"/>
      <subclass code="009" name="number of node labels below supported minimum"/>
      <subclass code="010" name="number of node labels exceeds supported maximum"/>
      <subclass code="011" name="number of node properties exceeds supported maximum"/>
      <subclass code="012"
                name="number of node type key labels below supported minimum"/>
      <subclass code="013"
                name="number of node type key labels exceeds supported maximum"/>
      <subclass code="014"
                name="number of edge type key labels below supported minimum"/>
      <subclass code="015"
                name="number of edge type key labels exceeds supported maximum"/>
   </class>
   <class category="X" code="G1" name="dependent object error">
      <subclass code="001" name="edges still exist"/>
      <subclass code="002" name="endpoint node is deleted"/>
      <subclass code="003" name="endpoint node not in current working graph"/>
   </class>
   <class category="X" code="G2" name="graph type violation"/>
</conditions>
